import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import AOSInitializer from '@/components/AOSInitializer';
import ThemeWrapper from '@/components/ThemeWrapper'; // ⬅️ gunakan ini

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] });

export const metadata: Metadata = {
  title: 'JAN Nusantara',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className}`}>
        <ThemeWrapper>
          <AOSInitializer />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
